global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "offline_api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "qdrant_vector_store"
    static_configs:
      - targets: ["vector-db:6333"]
    metrics_path: "/metrics"
    scrape_interval: 15s
